"""Replaceable feedback repository contract."""

from __future__ import annotations

from typing import Protocol

from conversation_agent.storage.models import (
    FeedbackUpdate,
    GeneratedReplyRecord,
    NewGeneratedReply,
)


class FeedbackRepository(Protocol):
    def initialize(self) -> None:
        """Create or migrate local storage."""
        ...

    def create_generated_reply(self, reply: NewGeneratedReply) -> int:
        """Persist a generated reply before Telegram delivery."""
        ...

    def mark_delivery(
        self,
        reply_id: int,
        *,
        status: str,
        sent_message_id: int | None = None,
        sent_at: str | None = None,
    ) -> bool:
        """Update delivery state and the Telegram message ID."""
        ...

    def save_feedback(self, reply_id: int, feedback: FeedbackUpdate) -> bool:
        """Store reviewed feedback for a generated reply."""
        ...

    def get_reply(self, reply_id: int) -> GeneratedReplyRecord | None:
        """Return one generated reply, if it exists."""
        ...

    def sent_message_ids(self, dialog_id: int) -> set[int]:
        """Return Telegram IDs known to have been generated by the agent."""
        ...

    def reviewed_replies(self) -> list[GeneratedReplyRecord]:
        """Return replies with explicit feedback in deterministic order."""
        ...
